name: Compile & test contracts
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Compile contracts
      run: npx hardhat compile
      env:
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        ROPSTEN_PRIVATE_KEY: ${{ secrets.ROPSTEN_PRIVATE_KEY }}
    - name: Test contracts
      run: npx hardhat test
      env:
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        ROPSTEN_PRIVATE_KEY: ${{ secrets.ROPSTEN_PRIVATE_KEY }}